#!/usr/bin/env python3


lines = []
lines.append("*---------------*---------------*---------------*---------------*---------------*")
lines.append("*   bbbbbb      *   iiiiiiiii   *   nnn     n   *     ggg       *     oooo      *")
lines.append("*   b     b     *       i       *   n  n    n   *   gg   gg     *    o    o     *")
lines.append("*   bbbbbb      *       i       *   n   n   n   *   g           *    o    o     *")
lines.append("*   b     b     *       i       *   n    n  n   *  gg   gg      *    o    o     *")
lines.append("*   b     b     *       i       *   n     n n   *   g     g     *    o    o     *")
lines.append("*   bbbbbb      *   iiiiiiiii   *   n      nn   *    ggggg      *     oooo      *")
lines.append("*               *               *               *               *               *")
lines.append("*---------------*---------------*---------------*---------------*---------------*")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*---------------*---------------*---------------*---------------*---------------*")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *     FREE      *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *     SPACE     *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*---------------*---------------*---------------*---------------*---------------*")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*---------------*---------------*---------------*---------------*---------------*")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*               *               *               *               *               *")
lines.append("*---------------*---------------*---------------*---------------*---------------*")

for line in lines:
	print(line)
